spring:
  application:
    name: wallet-service
  config:
    activate:
      on-profile: default
  datasource:
    url: jdbc:postgresql://localhost:5433/wallet_service?currentSchema=wallet
    username: wallet_user
    password: wallet_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  flyway:
    enabled: true
    default-schema: wallet
    schemas: wallet
    baseline-on-migrate: true
    locations: classpath:db/migration
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

logging:
  level:
    root: INFO

server:
  port: 8080

aws:
  region: us-east-1
  access-key: test
  secret-key: test
  sqs:
    deposit-queue-url: http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/deposit_queue

wallet:
  topics:
    withdraw: withdraw
    deposit: deposit
    transfer: transfer
    
