version: "3.8"

networks:
  ls:
    name: ls


services:
  postgres:
    image: postgres:14
    container_name: wallet-db
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  wallet_redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  pgdata:
